Add timeout to channel builder
graknlabs/client-java pull request #710
Opened 2024-11-08 14:34 UTC by dmitrii-ubskii

## Usage and product changes

## Implementation

2024-11-08 15:39 UTC, dmitrii-ubskii commented on rust/src/connection/network/channel.rs
> +const TIMEOUT: Duration = Duration::from_secs(60);
Chosen arbitrarily. Anything less than a second or so is too strict for slow connections, but going significantly over a minute would probably be too long.

2024-11-14 18:30 UTC, farost reviewed
Let's test queries

2024-11-18 12:28 UTC, dmitrii-ubskii commented on rust/src/connection/network/channel.rs
> +const TIMEOUT: Duration = Duration::from_secs(60);
The query does time out if the server does not respond within this time (tested by adding a `sleep(60000)` in `TransactionService::respond()` on the server side).

The default transaction timeout is 5 minutes. I'd extend this timeout to 10 minutes or even an hour.

Ideally we'd have a connection builder that would let the user specify the desired request timeout, but that would take a lot longer.

2024-11-19 16:13 UTC, farost requested changes
Waiting for the timeout value update

2025-03-25 21:06 UTC, closed without merging